language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  
branches:
  only:
    - master
    - working

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - jamie.hannaford@rackspace.com
    - glen.campbell@rackspace.com
